In [1]:
import numpy as np

In [2]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
xy

array([[  73.,   80.,   75.,  152.],
       [  93.,   88.,   93.,  185.],
       [  89.,   91.,   90.,  180.],
       [  96.,   98.,  100.,  196.],
       [  73.,   66.,   70.,  142.],
       [  52.,   46.,   55.,  101.]], dtype=float32)

In [3]:
x_data = xy[:,0:-1]
x_data

array([[  73.,   80.,   75.],
       [  93.,   88.,   93.],
       [  89.,   91.,   90.],
       [  96.,   98.,  100.],
       [  73.,   66.,   70.],
       [  52.,   46.,   55.]], dtype=float32)

In [4]:
y_data = xy[:,[-1]]
y_data

array([[ 152.],
       [ 185.],
       [ 180.],
       [ 196.],
       [ 142.],
       [ 101.]], dtype=float32)

In [5]:
# Make sure the shape and data are OK
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data, len(y_data))

((6, 3), array([[  73.,   80.,   75.],
       [  93.,   88.,   93.],
       [  89.,   91.,   90.],
       [  96.,   98.,  100.],
       [  73.,   66.,   70.],
       [  52.,   46.,   55.]], dtype=float32), 6)
((6, 1), array([[ 152.],
       [ 185.],
       [ 180.],
       [ 196.],
       [ 142.],
       [ 101.]], dtype=float32), 6)


In [6]:
import tensorflow as tf

In [7]:
# for reproducibility
tf.set_random_seed(777)

In [8]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [9]:
W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [10]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b

In [11]:
# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [12]:
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [13]:
# Launch the graph in a session
sess = tf.Session()

In [14]:
# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())

In [15]:
# Set up feed_dict variables inside the loop
for step in range(20001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 5000 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

(0, 'Cost: ', 20369.459, '\nPrediction:\n', array([[ 22.04806328],
       [ 21.61978722],
       [ 24.09669304],
       [ 22.29300499],
       [ 18.6339016 ],
       [  6.46427727]], dtype=float32))
(5000, 'Cost: ', 1.5353576, '\nPrediction:\n', array([[ 152.95591736],
       [ 184.15989685],
       [ 181.49481201],
       [ 194.6179657 ],
       [ 143.14367676],
       [  99.53708649]], dtype=float32))
(10000, 'Cost: ', 0.92545462, '\nPrediction:\n', array([[ 152.30474854],
       [ 184.40440369],
       [ 181.17381287],
       [ 194.66770935],
       [ 143.25553894],
       [ 100.3868866 ]], dtype=float32))
(15000, 'Cost: ', 0.70512038, '\nPrediction:\n', array([[ 152.16125488],
       [ 184.41134644],
       [ 181.06819153],
       [ 194.80149841],
       [ 143.09919739],
       [ 100.73068237]], dtype=float32))
(20000, 'Cost: ', 0.57387918, '\nPrediction:\n', array([[ 152.12464905],
       [ 184.37835693],
       [ 181.01545715],
       [ 194.92720032],
       [ 142.92462158],
    

In [16]:
# Ask my score
print("Your score will be ", sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))
print("Other scores will be ", sess.run(hypothesis, feed_dict={X: [[60,70,110], [90, 100, 80]]}))

('Your score will be ', array([[ 181.42991638]], dtype=float32))
('Other scores will be ', array([[ 124.98974609],
       [ 189.14985657]], dtype=float32))
