In [1]:
import numpy as np

In [2]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
xy

# 1번째 학생이 1번째 시험에서 73점을 받음
# 1번째 학생이 2번째 시험에서 80점을 받음
# 1번째 학생이 3번째 시험에서 75점을 받음
# 1번째 학생이 기말고사에서 152점을 받음

array([[  73.,   80.,   75.,  152.],
       [  93.,   88.,   93.,  185.],
       [  89.,   91.,   90.,  180.],
       [  96.,   98.,  100.,  196.],
       [  73.,   66.,   70.,  142.],
       [  53.,   46.,   55.,  101.],
       [  69.,   74.,   77.,  149.],
       [  47.,   56.,   60.,  115.],
       [  87.,   79.,   90.,  175.],
       [  79.,   70.,   88.,  164.],
       [  69.,   70.,   73.,  141.],
       [  70.,   65.,   74.,  141.],
       [  93.,   95.,   91.,  184.],
       [  79.,   80.,   73.,  152.],
       [  70.,   73.,   78.,  148.],
       [  93.,   89.,   96.,  192.],
       [  78.,   75.,   68.,  147.],
       [  81.,   90.,   93.,  183.],
       [  88.,   92.,   86.,  177.],
       [  78.,   83.,   77.,  159.],
       [  82.,   86.,   90.,  177.],
       [  86.,   82.,   89.,  175.],
       [  78.,   83.,   85.,  175.],
       [  76.,   83.,   71.,  149.],
       [  96.,   93.,   95.,  192.]], dtype=float32)

In [3]:
x_data = xy[:,0:-1]
x_data

array([[  73.,   80.,   75.],
       [  93.,   88.,   93.],
       [  89.,   91.,   90.],
       [  96.,   98.,  100.],
       [  73.,   66.,   70.],
       [  53.,   46.,   55.],
       [  69.,   74.,   77.],
       [  47.,   56.,   60.],
       [  87.,   79.,   90.],
       [  79.,   70.,   88.],
       [  69.,   70.,   73.],
       [  70.,   65.,   74.],
       [  93.,   95.,   91.],
       [  79.,   80.,   73.],
       [  70.,   73.,   78.],
       [  93.,   89.,   96.],
       [  78.,   75.,   68.],
       [  81.,   90.,   93.],
       [  88.,   92.,   86.],
       [  78.,   83.,   77.],
       [  82.,   86.,   90.],
       [  86.,   82.,   89.],
       [  78.,   83.,   85.],
       [  76.,   83.,   71.],
       [  96.,   93.,   95.]], dtype=float32)

In [4]:
y_data = xy[:,[-1]]
y_data

array([[ 152.],
       [ 185.],
       [ 180.],
       [ 196.],
       [ 142.],
       [ 101.],
       [ 149.],
       [ 115.],
       [ 175.],
       [ 164.],
       [ 141.],
       [ 141.],
       [ 184.],
       [ 152.],
       [ 148.],
       [ 192.],
       [ 147.],
       [ 183.],
       [ 177.],
       [ 159.],
       [ 177.],
       [ 175.],
       [ 175.],
       [ 149.],
       [ 192.]], dtype=float32)

In [5]:
# Make sure the shape and data are OK
print(x_data.shape, x_data, len(x_data)) # 25명의 학생이 3번의 시험을 봄
print(y_data.shape, y_data, len(y_data)) # 25명의 학생이 기말고사를 1번만 봄

((25, 3), array([[  73.,   80.,   75.],
       [  93.,   88.,   93.],
       [  89.,   91.,   90.],
       [  96.,   98.,  100.],
       [  73.,   66.,   70.],
       [  53.,   46.,   55.],
       [  69.,   74.,   77.],
       [  47.,   56.,   60.],
       [  87.,   79.,   90.],
       [  79.,   70.,   88.],
       [  69.,   70.,   73.],
       [  70.,   65.,   74.],
       [  93.,   95.,   91.],
       [  79.,   80.,   73.],
       [  70.,   73.,   78.],
       [  93.,   89.,   96.],
       [  78.,   75.,   68.],
       [  81.,   90.,   93.],
       [  88.,   92.,   86.],
       [  78.,   83.,   77.],
       [  82.,   86.,   90.],
       [  86.,   82.,   89.],
       [  78.,   83.,   85.],
       [  76.,   83.,   71.],
       [  96.,   93.,   95.]], dtype=float32), 25)
((25, 1), array([[ 152.],
       [ 185.],
       [ 180.],
       [ 196.],
       [ 142.],
       [ 101.],
       [ 149.],
       [ 115.],
       [ 175.],
       [ 164.],
       [ 141.],
       [ 141.],
       [ 184.],
 

In [6]:
import tensorflow as tf

In [7]:
# for reproducibility
tf.set_random_seed(777)

In [8]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [9]:
W = tf.Variable(tf.random_normal([3,1]), name='weight') 
b = tf.Variable(tf.random_normal([1]), name='bias')

In [10]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b # 행렬곱에서 행과 열의 갯수는 (25,3) * (3,1) = (25,1) 이다.

In [11]:
# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [12]:
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [13]:
# Launch the graph in a session
sess = tf.Session()

In [14]:
# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())

In [15]:
# Set up feed_dict variables inside the loop
for step in range(20001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 5000 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

(0, 'Cost: ', 21027.002, '\nPrediction:\n', array([[ 22.04806328],
       [ 21.61978722],
       [ 24.09669304],
       [ 22.29300499],
       [ 18.6339016 ],
       [  7.2669735 ],
       [ 12.33102989],
       [  3.15051103],
       [ 14.34794426],
       [  4.25342369],
       [ 14.48570824],
       [ 10.67806816],
       [ 28.80463982],
       [ 29.29880333],
       [ 11.23783684],
       [ 18.6465435 ],
       [ 31.18945122],
       [ 13.34466362],
       [ 28.84174156],
       [ 25.66280937],
       [ 15.08476067],
       [ 16.79836845],
       [ 15.92455101],
       [ 31.36112022],
       [ 24.98636436]], dtype=float32))
(5000, 'Cost: ', 8.4423428, '\nPrediction:\n', array([[ 152.94322205],
       [ 185.31620789],
       [ 181.74119568],
       [ 198.42134094],
       [ 141.39759827],
       [ 105.37388611],
       [ 148.98756409],
       [ 111.00701141],
       [ 174.23933411],
       [ 162.74023438],
       [ 143.48449707],
       [ 142.38879395],
       [ 187.23147583],
     

In [16]:
# Ask my score
print("Your score will be ", sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))
print("Other scores will be ", sess.run(hypothesis, feed_dict={X: [[60,70,110], [90, 100, 80]]}))

('Your score will be ', array([[ 186.60369873]], dtype=float32))
('Other scores will be ', array([[ 182.18225098],
       [ 175.23745728]], dtype=float32))
