In [1]:
import numpy as np

In [2]:
X = np.array([1,2])
X

array([1, 2])

In [3]:
print(X.shape, X.ndim)

(2,) 1


In [4]:
W = np.array([[3,4,5],[6,7,8]])
W

array([[3, 4, 5],
       [6, 7, 8]])

In [5]:
Y = np.dot(X, W)
Y

array([15, 18, 21])

In [6]:
print(Y.shape, Y.ndim)

(3,) 1
