### Output layer of ANN for 
### Classification use it's activate function Softmax function.
### Regression use it's activate function Identity function.

In [1]:
import numpy as np

In [2]:
def softmax(x):
    return np.exp(x) / np.sum(np.exp(x))

In [3]:
a = np.array([0.3,2.9,4.0])
a

array([0.3, 2.9, 4. ])

In [4]:
softmax(a)

array([0.01821127, 0.24519181, 0.73659691])

In [5]:
b = np.array([1010,1000,990])
b

array([1010, 1000,  990])

In [6]:
softmax(b)

/Users/rwoo/02_WorkSpace/13_DeepLearning_WorkSpace/DeepLearning-Study/99_Utility/venv/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  
/Users/rwoo/02_WorkSpace/13_DeepLearning_WorkSpace/DeepLearning-Study/99_Utility/venv/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([nan, nan, nan])

In [7]:
def softmax(x):
    x = x - np.max(x)
    return np.exp(x) / np.sum(np.exp(x))

In [8]:
softmax(b)

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])

### since y = exp(x) is Monotonically increased function.
### softmax input/output layer's sort order of Nueral is same.
### So use softmax on learning but not on inferencing.

### In Classification, use softmax as activate function and set output layer's count as classification's counts.